# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ff2481a8e7e24397ae93a9fd441a465ac96912d6b97a166a03ee26c7add7a8c8edeb66ce89739c19e16721d8c0c7ed3b823726370bc33b0f71de2d562b1bfd4

test:
  secret_key_base: 8b543db38def917303d7d4182d25254221b99709c90b3724617ba65fa42d3d829b058d175e19c6b57eacee7bb4e01cd801f44aeeba4a45990298eacecea42c3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
